dbt_transformation:
  outputs:
    dev:
      dbname: postgres
      host: aws-0-eu-central-1.pooler.supabase.com
      pass: supabase*123
      port: 5432
      schema: transformed_data
      threads: 1
      type: postgres
      user: postgres.mcmuajjidcvctpvoigku
  target: dev
